config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
     flash[:success] = "Article was updated"
     redirect_to article_path(@article)
    else
     flash[:success] = "Article was not updated"
     render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "Article was deleted"
    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-6">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-large' %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>
<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
            </div>
            <div class="article-actions">
                <%= link_to "Show", article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-success" %>
                <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
  <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
</div>

<div class="clearfix"></div>
<div class="col-xs-8 col-xs-offset-2">
  <%= link_to 'Back', articles_path, :class => "btn btn-xs btn-success" %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog Test", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(@article.errors.count, "error") %>
                    prohibited this article from being saved:
                </h2>
                <div class="panel-body">
                    <ul>
                        <% @article.errors.full_messages.each do |msg|%>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
</div>